### PR TITLE
Make all get*Unchecked methods public

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by martint** [comment]
If the bounds checks are an issue, we should consider removing them all. I'm not sure I like having two variants of the API.

**Comment by cberner** [comment]
For the bit unpacking code I'm working on they reduce efficiency by ~10%

**Comment by electrum** [comment]
Should these be moved to static methods in a separate class, like `UnsafeSlice`? Currently, even though slice uses `Unsafe`, usages of it should be completely safe (barring bugs in `Slice` itself). We intentionally don't expose anything that would allow arbitrary memory access or corruption.

**Comment by electrum** [comment]
I also strongly disagree with removing the checks from everything, since that means every single call site needs to be audited as carefully as C code.

**Comment by martint** [comment]
> I also strongly disagree with removing the checks from everything, since that means every single call site needs to be audited as carefully as C code.

If it has that big of an impact, we're eventually going to have to replace all callsites to use the unchecked versions.

**Comment by cberner** [comment]
I think we should leave the bounds checks in get* at least for the moment. We've had several Presto bugs that would have resulted in the whole VM crashing without those. I feel like it's better to have both and only use get*Unchecked in places were it can be proven the bounds checks are unnecessary

**Comment by cberner** [comment]
Updated

**Comment by dain** [comment]
Looks good

**Pull request merged**
