### PR TITLE
Slice 2.0 for JDK21

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by GavinRay97** [comment]
Heya, not super familiar with the internals of `slice`, but I was wondering whether you might be able to get use out of the UTF-8 string methods in Panama FFM?

There are methods to allocate a UTF-8 string and to convert to a UTF-8 string

NOTE: These recently got changed to `getString()` and `allocateString()` so that'll be in the final JDK-21 build I believe
- https://github.com/openjdk/panama-foreign/pull/836

Something like:
```java
    public static Slice utf8Slice(String string)
    {
        return Slice.createSlice(GLOBAL_ARENA.allocateUtf8String(string));
    }
```

```java
   // For SliceUtf8#toUpperCase/toLowerCase
    public static Slice toUpperCase(Slice utf8) {
        String uppercased = utf8.getMemory().getUtf8String(0).toUpperCase();
        return Slices.utf8Slice(uppercased);
    }

    public static Slice reverse(Slice utf8) {
        String original = utf8.getMemory().getUtf8String(0);
        String reversedString = new StringBuilder(original).reverse().toString();
        return Slices.utf8Slice(reversedString);
    }
```

Also potentially `copyUtf8SequenceUnsafe()` could be simplified, but there might be a reason why it's written how it is:
```java
    private static void copyUtf8SequenceUnsafe(Slice source, int sourcePosition, Slice destination,
            int destinationPosition, int length) {
        if (length <= 0 || length > 6) {
            throw new IllegalStateException("Invalid code point length " + length);
        }
        
        destination.setBytes(destinationPosition, source, sourcePosition, length);
    }
```

**Comment by wendigo** [comment]
@GavinRay97 definitely we will use whatever is there in the API. Thanks for the pointers!

**Comment by wendigo** [comment]
@GavinRay97 Unfortunately this has different semantics due to a string being NULL-terminated (length is +1)

**Comment by wendigo** [comment]
The correct way would be something like that:

```
public static Slice utf8Slice(String string)
{
      MemorySegment memorySegment = GLOBAL_ARENA.allocateUtf8String(string);
      return Slice.createSlice(memorySegment.asSlice(0, memorySegment.byteSize() - 1));
}
```

**Comment by dain** [comment]
@GavinRay97 are you considering adding support for non-null terminated native strings.  In some systems UTF8 is not null terminated (since zero is a valid character) and it instead length prefixed, so having support for writing to a memory segment without the null would be nice.

**Pull request closed without merging**
