### PR TITLE
Add comment for readSlice method in SliceInput 

### PR DESCRIPTION
**Pull request by viczhang861**
BasicSliceInput returns a slice that is a view
over the input slice.

ChunkedSliceInput and InputStreamSliceInput
create a new copy of subregion.

### CODE REVIEW

**Review by arhimondr — APPROVED** [review]

**Comment by viczhang861** [comment]
cc. @findepi @pettyjamesm This will fix incorrect memory retained size for Page serde in spilling.  The retained memory size for a page with N blocks of `VariableWidthBlock` will be enlarged by N times because every `VariableWidthBlock` will call `readSlice` from `BasicSliceInput`.

**Comment by viczhang861** [comment]
Hi @dain @martint @electrum, you contributed to `BasicSliceInput` before.  Please help to review, thanks.

**Comment by martint** [comment]
This is by design. It the caller needs a compact slice (it can check with `Slice.isCompact()`), it should make a copy of it via `Slices.copyOf`.

**Comment by arhimondr** [comment]
@martint 

> This is by design. It the caller needs a compact slice (it can check with Slice.isCompact()), it should make a copy of it via Slices.copyOf.

The comment is a little confusing

> Returns a new slice of this buffer's sub-region ...

https://github.com/airlift/slice/blob/master/src/main/java/io/airlift/slice/SliceInput.java#L149

Also the other two implementations return a copy:

https://github.com/airlift/slice/blob/master/src/main/java/io/airlift/slice/InputStreamSliceInput.java#L243
https://github.com/airlift/slice/blob/master/src/main/java/io/airlift/slice/ChunkedSliceInput.java#L205

**Comment by martint** [comment]
> Returns a new slice of this buffer's sub-region ...

It could be made clearer, but "new slice" doesn't mean "a copy". The method doesn't impose constraints on whether the result keeps a reference to the underlying slice.

> Also the other two implementations return a copy:

That's because returning a view is not applicable to those. SliceInputStream operates on a stream of bytes, ChunkedSliceInput may need to read across buffer boundaries.

**Comment by pettyjamesm** [comment]
@martint it makes sense that avoiding a data copy here is by design- but I’ve been burned by this behavior personal and incidentally stumbled across the retained size quirk in presto within the same week. How about instead of forcing a copy in `readSlice`, we add a method to SliceInput called something like `readIntoNewSlice`? Implementations that already copy can share their current implementation for the new behavior, and callers can opt-in if they need copies.

On the subject of serialized pages, it’s unfortunate that PagesSerDe forces the initial copy out of an InputStream into a Slice, because that’s what makes the VariableWidthBlock decoding sensitive to adding _another _ copy even though all of the other encodings copy data out into primitive arrays already. Anyway, that’s a thought for a different GitHub project and different PR. I agree that avoiding copies is a feature that can be desirable, but so is forcing a copy to avoid over-retaining- caller’s choice depending on the usage context. The remaining question is whether extending the interface is desirable or whether forcing callers to continue to have to copy the returned Slice if they need it is preferred.

**Comment by pettyjamesm** [comment]
In light of the other comments, I actually do agree that blind copying if you don’t want to share the backing Slice at the usage site of SliceInput is less ideal than extending the interface because it does seem likely to introduce even more redundant copies when they aren’t needed just to handle the one case where they are (or might be desirable, at least).

**Comment by viczhang861** [comment]
@martint Thank you for explanation. I added comment to let caller know slice could be NON_COMPACT

**Pull request merged**
